### ISSUE TITLE
Condition for RegExp

### ISSUE THREAD

**Issue by vampyar** [gre/json-beautify#1]
For case 'object' after 101 line code add condition for RegExp
```javascript
case 'object' : 
            if (Object.prototype.toString.apply(value) === '[object RegExp]') {
                partial[gap] = value;
                gap = mind;
                return value;
            }
```

**Comment by rjmunro** [comment]
This doesn't seem to be compatible with the JSON spec - there is no special handling for RegExps

**Comment by gre** [comment]
agreed with @rjmunro , no special case to handle, we're based on the same implementation of `JSON.stringify`.

you might want to fork this lib in your side if you want something more custom.
