### ISSUE TITLE
TypeScript Compatibility 

### ISSUE THREAD

**Issue by Alaboudi1** [gre/json-beautify#6]
It seems that TypeScript tries to infer the type for `replacer` from this function call.
https://github.com/gre/json-beautify/blob/c3f4c6287982148f7d5b862fea70489cc14c6d09/index.js#L218

When call beautify with `replacer` = `null` like in the examples, it throws an error

TypeScript error in /workspace/API-Guide/src/App.tsx(16,45):
Argument of type 'null' is not assignable to parameter of type 'object | Function | any[]'.  TS2345

   16 |             beautify(obj, null, 2, 100))

**Comment by green3g** [comment]
As a workaround:
```javascript
        const replacer : any = null;
        beautify(data, replacer, 4, 80)
```
